"use client";

import { 
  LogOut, Menu, Search, Plus, Edit2, Trash2, Eye, Tag, Layers, FileText, Grid, Star, Heart, 
  MessageSquare, Sun, Moon, BookOpen, Bold, Italic, Underline, Strikethrough, Heading, Heading2, 
  Heading3, List, ListOrdered, AlignLeft, AlignCenter, AlignRight, Link, Image, Upload, Code, 
  Quote, X, ThumbsUp, ThumbsDown, Share2, Bookmark, ChevronRight, Calendar, Phone, Mail, 
  MapPin, Twitter, Github, Linkedin, Send, HelpCircle, Lightbulb, Users, Bell, Settings,
  AlertTriangle, Info, MessageCircle, BarChart3, Wrench, DollarSign, TrendingUp, Zap, CheckCircle,
  XCircle, Map, Thermometer, Car, Bike, Fuel, Smartphone, Target, Weight, Timer, Mountain,
  Sparkles, Rocket, Palette, Scale, Snowflake, Shield, TrendingDown, Clock, Gauge, Route,
  Calculator, Coins, Activity, Edit
} from "lucide-react";

const ICONS = {
  logout: LogOut,
  menu: Menu,
  search: Search,
  plus: Plus,
  edit: Edit2,
  trash: Trash2,
  eye: Eye,
  tag: Tag,
  layers: Layers,
  file: FileText,
  grid: Grid,
  star: Star,
  heart: Heart,
  message: MessageSquare,
  sun: Sun,
  moon: Moon,
  book: BookOpen,
  // Editor icons
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  heading: Heading,
  "heading-2": Heading2,
  "heading-3": Heading3,
  list: List,
  "list-ordered": ListOrdered,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  link: Link,
  image: Image,
  upload: Upload,
  code: Code,
  quote: Quote,
  x: X,
  // Blog interaction icons
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "share-2": Share2,
  bookmark: Bookmark,
  "chevron-right": ChevronRight,
  calendar: Calendar,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  twitter: Twitter,
  github: Github,
  linkedin: Linkedin,
  send: Send,
  "help-circle": HelpCircle,
  lightbulb: Lightbulb,
  users: Users,
  bell: Bell,
  settings: Settings,
  "alert-triangle": AlertTriangle,
  info: Info,
  "message-circle": MessageCircle,
  // Fuel calculator icons
  "bar-chart": BarChart3,
  wrench: Wrench,
  "dollar-sign": DollarSign,
  "trending-up": TrendingUp,
  zap: Zap,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  map: Map,
  thermometer: Thermometer,
  car: Car,
  bike: Bike,
  fuel: Fuel,
  smartphone: Smartphone,
  target: Target,
  weight: Weight,
  timer: Timer,
  mountain: Mountain,
  sparkles: Sparkles,
  rocket: Rocket,
  palette: Palette,
  scale: Scale,
  snowflake: Snowflake,
  shield: Shield,
  "trending-down": TrendingDown,
  clock: Clock,
  gauge: Gauge,
  route: Route,
  calculator: Calculator,
  coins: Coins,
  activity: Activity,
  pencil: Edit,
  // semantic aliases
  dashboard: Grid,
  posts: FileText,
  categories: Layers,
};

export default function Icon({ name, className, ...props }) {
  const Comp = ICONS[name];
  if (!Comp) return null;
  return <Comp className={className} {...props} />;
}
